### ISSUE TITLE
Skip and Take

### ISSUE THREAD

**Issue by kiwiingenuity** [chsakell/multi-client-api#1]
On all your controllers you have Skip(page).Take(pageSize);
Should it not be 
.Skip((page -1) \* pageSize).Take(pageSize);

**Comment by chsakell** [comment]
Yup, my bad. I was working with some custom repositories first where pagination was supported and then I forgot to change it. I committed the fixes <a href="https://github.com/chsakell/multi-client-api/commit/7a2ece202fe66630617a5ce0ceea8cca3516eb4a" target="_blank">here</a>.
Thanks.
